export interface User { uid: string; email: string; displayName: string; photoURL?: string; role: 'admin'|'moderator'|'user'; isOnline: boolean; lastSeen: string; settings: UserSettings; createdAt: string; }
export interface UserSettings { audioEnabled: boolean; videoEnabled: boolean; noiseSuppressionEnabled: boolean; virtualBackgroundEnabled: boolean; theme: 'light'|'dark'|'system'; language: string; notifications: { meetingReminders: boolean; chatMessages: boolean; participantJoins: boolean; participantLeaves: boolean; }; }
export interface Meeting { id: string; code: string; title: string; description?: string; hostId: string; hostName: string; status: 'scheduled'|'active'|'ended'|'cancelled'; scheduledAt?: string; startedAt?: string; endedAt?: string; duration?: number; settings: MeetingSettings; participants: string[]; waitingRoom: string[]; bannedUsers: string[]; recordingEnabled: boolean; recordingId?: string; isLocked: boolean; hasPassword?: boolean; maxParticipants: number; createdAt: string; }
export interface MeetingSettings { waitingRoomEnabled: boolean; hostApprovalRequired: boolean; chatEnabled: boolean; screenShareEnabled: boolean; fileShareEnabled: boolean; whiteboardEnabled: boolean; recordingEnabled: boolean; muteOnEntry: boolean; videoOnEntry: boolean; allowParticipantRename: boolean; }
export interface Participant { uid: string; meetingId: string; displayName: string; photoURL?: string; role: 'host'|'co-host'|'participant'; status: 'waiting'|'active'|'left'|'removed'|'banned'; audioEnabled: boolean; videoEnabled: boolean; screenSharing: boolean; handRaised: boolean; joinedAt: string; connectionQuality: 'excellent'|'good'|'poor'|'disconnected'; }
export interface Message { id: string; meetingId: string; senderId: string; senderName: string; senderPhotoURL?: string; content: string; type: 'text'|'file'|'image'|'system'; fileURL?: string; fileName?: string; fileSize?: number; reactions: Record<string,string[]>; readBy: string[]; editedAt?: string; deletedAt?: string; createdAt: string; }
export interface FileShare { id: string; meetingId: string; uploaderId: string; uploaderName: string; name: string; type: string; size: number; url: string; thumbnailURL?: string; createdAt: string; }
export interface Recording { id: string; meetingId: string; meetingTitle: string; hostId: string; startedAt: string; endedAt?: string; duration?: number; fileURL?: string; fileSize?: number; status: 'recording'|'processing'|'available'|'failed'; }
export interface Notification { id: string; userId: string; type: string; title: string; body: string; data?: Record<string,string>; read: boolean; createdAt: string; }
export interface SignalingMessage { type: 'offer'|'answer'|'ice-candidate'|'user-joined'|'user-left'; senderId: string; receiverId?: string; payload: unknown; timestamp: number; }
