import { randomBytes, scryptSync, timingSafeEqual } from 'crypto';
import { Request, Response } from 'express';
import { FieldValue, Timestamp } from 'firebase-admin/firestore';
import { db } from '../config/firebase';
import { AuthenticatedRequest, MeetingSettings } from '../types';
import { generateMeetingCode } from '../utils/meetingCode';
import { sendError, sendPaginated, sendSuccess } from '../utils/response';

const DEFAULT_SETTINGS: MeetingSettings={waitingRoomEnabled:true,hostApprovalRequired:false,chatEnabled:true,screenShareEnabled:true,fileShareEnabled:true,whiteboardEnabled:true,recordingEnabled:false,muteOnEntry:false,videoOnEntry:true,allowParticipantRename:true};
const safe=(d:any)=>{const {password:_,...rest}=d;return rest;};
const uid=(req:AuthenticatedRequest,res:Response)=>{if(!req.user?.uid){sendError(res,'Authentication required',401);return null;}return req.user.uid;};
const hash=(p:string)=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(p,salt,64).toString('hex')}`;};
const verify=(p:string,s?:string)=>{if(!s)return true;const [salt,h]=s.split(':');if(!salt||!h)return false;const a=Buffer.from(h,'hex'),b=scryptSync(p,salt,64);return a.length===b.length&&timingSafeEqual(a,b);};
const meetingRef=(id:string)=>db.collection('meetings').doc(id);

export const getIceServers=async(_req:Request,res:Response)=>{const ice:any[]=[{urls:'stun:stun.l.google.com:19302'}];const turnUrl=process.env.TURN_SERVER; if(turnUrl&&process.env.TURN_USERNAME&&process.env.TURN_CREDENTIAL)ice.push({urls:turnUrl.split(',').map(x=>x.trim()),username:process.env.TURN_USERNAME,credential:process.env.TURN_CREDENTIAL});sendSuccess(res,{iceServers:ice});};

export const createMeeting=async(req:AuthenticatedRequest,res:Response)=>{const id=uid(req,res);if(!id)return;const title=String(req.body.title||'').trim();if(!title)return sendError(res,'Title is required',422);const max=Math.min(250,Math.max(2,Number(req.body.maxParticipants||100)));const scheduled=req.body.scheduledAt?Timestamp.fromDate(new Date(req.body.scheduledAt)):null;const code=generateMeetingCode();const ref=meetingRef(db.collection('meetings').doc().id);const settings={...DEFAULT_SETTINGS,...(req.body.settings||{})};if(typeof req.body.recordingEnabled==='boolean')settings.recordingEnabled=req.body.recordingEnabled;const now=FieldValue.serverTimestamp();const data:any={id:ref.id,code,title,hostId:id,hostName:req.user?.displayName||req.user?.email||'Host',status:scheduled?'scheduled':'active',settings,participants:[id],waitingRoom:[],bannedUsers:[],recordingEnabled:settings.recordingEnabled,isLocked:false,maxParticipants:max,createdAt:now,updatedAt:now,...(scheduled?{scheduledAt:scheduled}:{startedAt:now}),...(req.body.password?{password:hash(String(req.body.password))}:{})};await ref.set(data);await ref.collection('participants').doc(id).set({uid:id,meetingId:ref.id,displayName:data.hostName,role:'host',status:'active',audioEnabled:true,videoEnabled:true,screenSharing:false,handRaised:false,connectionQuality:'excellent',joinedAt:now});sendSuccess(res,safe(data),'Meeting created',201);};

export const listMeetings=async(req:AuthenticatedRequest,res:Response)=>{const id=uid(req,res);if(!id)return;const page=Math.max(1,Number(req.query.page||1)),limit=Math.min(50,Math.max(1,Number(req.query.limit||20)));try{const snapshot=await db.collection('meetings').where('participants','array-contains',id).limit(Math.min(50,page*limit)).get();const items=snapshot.docs.map(d=>safe(d.data())).sort((x,y)=>(y.createdAt?.toMillis?.()??0)-(x.createdAt?.toMillis?.()??0));const start=(page-1)*limit;sendPaginated(res,items.slice(start,start+limit),page,limit,items.length);}catch(error:any){const code=error?.code;const message=typeof error?.message==='string'?error.message:'Unable to load meetings';if(code===8||code==='resource-exhausted'){sendError(res,'Firestore read quota is exhausted. Please wait for the daily quota to reset or enable billing for the project.',503);return;}throw error;}};

export const getMeetingById=async(req:AuthenticatedRequest,res:Response)=>{const id=uid(req,res);if(!id)return;const s=await meetingRef(req.params.meetingId).get();if(!s.exists)return sendError(res,'Meeting not found',404);const d=s.data()!;if(d.hostId!==id&&!d.participants?.includes(id)&&!d.waitingRoom?.includes(id))return sendError(res,'Access denied',403);sendSuccess(res,safe(d));};
export const getMeetingByCode=async(req:AuthenticatedRequest,res:Response)=>{const code=String(req.params.code).trim().toLowerCase();const s=await db.collection('meetings').where('code','==',code).limit(1).get();if(s.empty)return sendError(res,'Meeting not found',404);const d=s.docs[0].data();sendSuccess(res,{id:d.id,code:d.code,title:d.title,hostName:d.hostName,status:d.status,isLocked:d.isLocked,maxParticipants:d.maxParticipants,waitingRoomEnabled:d.settings?.waitingRoomEnabled??true,passwordRequired:Boolean(d.password)});};

export const joinMeeting=async(req:AuthenticatedRequest,res:Response)=>{const id=uid(req,res);if(!id)return;const ref=meetingRef(req.params.meetingId);let result:any=null;await db.runTransaction(async tx=>{const s=await tx.get(ref);if(!s.exists)throw Object.assign(new Error('Meeting not found'),{statusCode:404});const d=s.data()!;if(d.bannedUsers?.includes(id))throw Object.assign(new Error('You are banned from this meeting'),{statusCode:403});if(['ended','cancelled'].includes(d.status))throw Object.assign(new Error('Meeting is no longer active'),{statusCode:409});if(d.hostId===id||d.participants?.includes(id)){result={status:'active',meeting:safe(d)};return;}if(d.isLocked)throw Object.assign(new Error('Meeting is locked'),{statusCode:423});if(!verify(String(req.body.password||''),d.password))throw Object.assign(new Error('Invalid meeting password'),{statusCode:401});const count=Array.isArray(d.participants)?d.participants.length:0;if(count>=Number(d.maxParticipants||100))throw Object.assign(new Error('Meeting is full'),{statusCode:409});const waiting=Boolean(d.settings?.waitingRoomEnabled||d.settings?.hostApprovalRequired);const next=waiting?'waiting':'active';const p=ref.collection('participants').doc(id);tx.set(p,{uid:id,meetingId:ref.id,displayName:req.user?.displayName||req.user?.email||'Participant',role:'participant',status:next,audioEnabled:!d.settings?.muteOnEntry,videoEnabled:Boolean(d.settings?.videoOnEntry),screenSharing:false,handRaised:false,connectionQuality:'good',joinedAt:FieldValue.serverTimestamp()});tx.update(ref,waiting?{waitingRoom:FieldValue.arrayUnion(id),updatedAt:FieldValue.serverTimestamp()}:{participants:FieldValue.arrayUnion(id),updatedAt:FieldValue.serverTimestamp(),...(d.status==='scheduled'?{status:'active',startedAt:FieldValue.serverTimestamp()}: {})});result={status:next,meeting:safe(d)};});if(!result)return sendError(res,'Unable to join meeting',500);sendSuccess(res,result,result.status==='waiting'?'Waiting for host approval':'Joined meeting');};

export const leaveMeeting=async(req:AuthenticatedRequest,res:Response)=>{const id=uid(req,res);if(!id)return;const ref=meetingRef(req.params.meetingId),s=await ref.get();if(!s.exists)return sendError(res,'Meeting not found',404);const d=s.data()!;if(d.hostId===id)return sendError(res,'Host must end the meeting',400);if(!d.participants?.includes(id)&&!d.waitingRoom?.includes(id))return sendError(res,'You are not in this meeting',404);const batch=db.batch();batch.update(ref,{participants:FieldValue.arrayRemove(id),waitingRoom:FieldValue.arrayRemove(id),updatedAt:FieldValue.serverTimestamp()});batch.set(ref.collection('participants').doc(id),{status:'left',leftAt:FieldValue.serverTimestamp()},{merge:true});await batch.commit();sendSuccess(res,null,'Left meeting');};

export const endMeeting=async(req:AuthenticatedRequest,res:Response)=>{const ref=meetingRef(req.params.meetingId),s=await ref.get();if(!s.exists)return sendError(res,'Meeting not found',404);if(s.data()!.status==='ended')return sendSuccess(res,{id:ref.id,status:'ended'},'Meeting already ended');await ref.update({status:'ended',endedAt:FieldValue.serverTimestamp(),updatedAt:FieldValue.serverTimestamp(),participants:[],waitingRoom:[]});const p=await ref.collection('participants').where('status','in',['active','waiting']).get();if(!p.empty){const batch=db.batch();p.docs.forEach(d=>batch.update(d.ref,{status:'left',leftAt:FieldValue.serverTimestamp()}));await batch.commit();}sendSuccess(res,{id:ref.id,status:'ended'},'Meeting ended');};

export const listParticipants=async(req:AuthenticatedRequest,res:Response)=>{const id=uid(req,res);if(!id)return;const s=await meetingRef(req.params.meetingId).get();if(!s.exists)return sendError(res,'Meeting not found',404);const d=s.data()!;if(d.hostId!==id&&!d.participants?.includes(id))return sendError(res,'Access denied',403);const p=await s.ref.collection('participants').where('status','in',['active','waiting']).get();sendSuccess(res,p.docs.map(x=>x.data()));};
export const meetingAnalytics=async(req:AuthenticatedRequest,res:Response)=>{const s=await meetingRef(req.params.meetingId).get();if(!s.exists)return sendError(res,'Meeting not found',404);const d=s.data()!,p=await s.ref.collection('participants').get(),rows=p.docs.map(x=>x.data());sendSuccess(res,{meetingId:s.id,status:d.status,participantCount:rows.length,activeParticipants:rows.filter(x=>x.status==='active').length,completedParticipants:rows.filter(x=>x.leftAt).length,durationMs:d.startedAt&&d.endedAt?Math.max(0,d.endedAt.toMillis()-d.startedAt.toMillis()):null});};

const move=async(req:AuthenticatedRequest,res:Response,approve:boolean)=>{const ref=meetingRef(req.params.meetingId),id=req.params.userId,s=await ref.get();if(!s.exists)return sendError(res,'Meeting not found',404);if(!s.data()!.waitingRoom?.includes(id))return sendError(res,'Participant is not waiting',404);const batch=db.batch();batch.update(ref,{waitingRoom:FieldValue.arrayRemove(id),...(approve?{participants:FieldValue.arrayUnion(id)}:{}),updatedAt:FieldValue.serverTimestamp()});batch.set(ref.collection('participants').doc(id),{status:approve?'active':'removed',...(approve?{}:{leftAt:FieldValue.serverTimestamp()})},{merge:true});await batch.commit();sendSuccess(res,{userId:id,status:approve?'active':'denied'});};
export const approveParticipant=(req:AuthenticatedRequest,res:Response)=>move(req,res,true);export const denyParticipant=(req:AuthenticatedRequest,res:Response)=>move(req,res,false);
export const removeParticipant=async(req:AuthenticatedRequest,res:Response)=>{const ref=meetingRef(req.params.meetingId),id=req.params.userId,s=await ref.get();if(!s.exists)return sendError(res,'Meeting not found',404);if(s.data()!.hostId===id)return sendError(res,'Host cannot be removed',400);await ref.update({participants:FieldValue.arrayRemove(id),waitingRoom:FieldValue.arrayRemove(id),updatedAt:FieldValue.serverTimestamp()});await ref.collection('participants').doc(id).set({status:'removed',leftAt:FieldValue.serverTimestamp()},{merge:true});sendSuccess(res,{userId:id,status:'removed'});};
export const banParticipant=async(req:AuthenticatedRequest,res:Response)=>{const ref=meetingRef(req.params.meetingId),id=req.params.userId,s=await ref.get();if(!s.exists)return sendError(res,'Meeting not found',404);if(s.data()!.hostId===id)return sendError(res,'Host cannot be banned',400);await ref.update({participants:FieldValue.arrayRemove(id),waitingRoom:FieldValue.arrayRemove(id),bannedUsers:FieldValue.arrayUnion(id),updatedAt:FieldValue.serverTimestamp()});await ref.collection('participants').doc(id).set({status:'banned',leftAt:FieldValue.serverTimestamp()},{merge:true});sendSuccess(res,{userId:id,status:'banned'});};
export const lockMeeting=async(req:AuthenticatedRequest,res:Response)=>{const ref=meetingRef(req.params.meetingId);const s=await ref.get();if(!s.exists)return sendError(res,'Meeting not found',404);const locked=typeof req.body.locked==='boolean'?req.body.locked:!Boolean(s.data()!.isLocked);await ref.update({isLocked:locked,updatedAt:FieldValue.serverTimestamp()});sendSuccess(res,{locked});};
export const updateMeetingSettings=async(req:AuthenticatedRequest,res:Response)=>{const ref=meetingRef(req.params.meetingId),s=await ref.get();if(!s.exists)return sendError(res,'Meeting not found',404);const current=s.data()!.settings||DEFAULT_SETTINGS;const allowed=['waitingRoomEnabled','hostApprovalRequired','chatEnabled','screenShareEnabled','fileShareEnabled','whiteboardEnabled','recordingEnabled','muteOnEntry','videoOnEntry','allowParticipantRename'];const patch:any={};allowed.forEach(k=>{if(typeof req.body?.[k]==='boolean')patch[k]=req.body[k]});if(req.body?.settings&&typeof req.body.settings==='object')allowed.forEach(k=>{if(typeof req.body.settings[k]==='boolean')patch[k]=req.body.settings[k]});const settings={...current,...patch};await ref.update({settings,recordingEnabled:settings.recordingEnabled,updatedAt:FieldValue.serverTimestamp()});sendSuccess(res,{settings});};