import { Router } from 'express';
import { authenticate, requireHost } from '../middleware/auth';
import { meetingCreateLimiter } from '../middleware/rateLimiter';
import { sanitizeInput, validate, validateCreateMeeting } from '../middleware/validation';
import { createMeeting, getMeetings, getMeeting, getMeetingByCode, joinMeeting, approveParticipant, denyParticipant, leaveMeeting, endMeeting, removeParticipant, banUser, toggleLock, updateMeetingSettings, getParticipants, getMeetingAnalytics, getIceServers } from '../controllers/meetingController';
const r = Router();
r.use(authenticate);
r.get('/ice-servers', getIceServers);
r.get('/code/:code', getMeetingByCode);
r.post('/', meetingCreateLimiter, sanitizeInput, validateCreateMeeting, validate, createMeeting);
r.get('/', getMeetings);
r.get('/:meetingId', getMeeting);
r.post('/:meetingId/join', sanitizeInput, joinMeeting);
r.delete('/:meetingId/leave', leaveMeeting);
r.post('/:meetingId/end', requireHost, endMeeting);
r.get('/:meetingId/participants', getParticipants);
r.get('/:meetingId/analytics', requireHost, getMeetingAnalytics);
r.post('/:meetingId/approve/:userId', requireHost, approveParticipant);
r.post('/:meetingId/deny/:userId', requireHost, denyParticipant);
r.post('/:meetingId/remove/:userId', requireHost, removeParticipant);
r.post('/:meetingId/ban/:userId', requireHost, banUser);
r.put('/:meetingId/lock', requireHost, toggleLock);
r.put('/:meetingId/settings', requireHost, sanitizeInput, updateMeetingSettings);
export default r;
