'use client';

import { useEffect, useRef, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Mic, MicOff, Video, VideoOff, MonitorUp, MessageSquare, PhoneOff, Users, Shield, Copy, MoreHorizontal } from 'lucide-react';
import { api } from '../../../config/api';
import { firebaseAuth } from '../../../config/firebase';
import toast from 'react-hot-toast';

export default function MeetingRoom(){
  const {code}=useParams<{code:string}>();const router=useRouter();const videoRef=useRef<HTMLVideoElement>(null);const [audio,setAudio]=useState(true);const [video,setVideo]=useState(true);const [sharing,setSharing]=useState(false);const [chat,setChat]=useState(false);const [copied,setCopied]=useState(false);const [stream,setStream]=useState<MediaStream|null>(null);const [meeting,setMeeting]=useState<any>(null);const [status,setStatus]=useState('Connecting…');const [participants,setParticipants]=useState<any[]>([]);
  useEffect(()=>{let mounted=true;(async()=>{if(!firebaseAuth.currentUser){router.replace('/login');return}try{const meta=(await api.get<any>(`/meetings/code/${encodeURIComponent(String(code))}`)).data?.data;const joined=(await api.post<any>(`/meetings/${meta.id}/join`,{})).data?.data;if(!mounted)return;setMeeting({...meta,...joined?.meeting});setStatus(joined?.status==='waiting'?'Waiting for host approval':'Connected');if(joined?.status!=='waiting'){const media=await navigator.mediaDevices.getUserMedia({video:true,audio:true});if(mounted){setStream(media);if(videoRef.current)videoRef.current.srcObject=media}}}catch(e:any){if(mounted){setStatus('Unable to join');toast.error(e?.response?.data?.error||'Unable to join meeting')}}})();return()=>{mounted=false}},[code,router]);
  useEffect(()=>{if(videoRef.current&&stream)videoRef.current.srcObject=stream;return()=>stream?.getTracks().forEach(t=>t.stop())},[stream]);
  useEffect(()=>{if(!meeting?.id)return;api.get<any>(`/meetings/${meeting.id}/participants`).then(r=>setParticipants(r.data?.data||[])).catch(()=>{})},[meeting?.id]);
  const toggle=(kind:'audio'|'video')=>{if(!stream)return;stream.getTracks().filter(t=>t.kind===kind).forEach(t=>t.enabled=!t.enabled);kind==='audio'?setAudio(v=>!v):setVideo(v=>!v)};
  const copy=()=>{navigator.clipboard?.writeText(String(code));setCopied(true);setTimeout(()=>setCopied(false),1500)};
  const share=async()=>{try{const s=await navigator.mediaDevices.getDisplayMedia({video:true});setSharing(true);s.getVideoTracks()[0].onended=()=>setSharing(false)}catch{setSharing(false)}};
  const leave=async()=>{if(meeting?.id)try{await api.delete(`/meetings/${meeting.id}/leave`)}catch{};stream?.getTracks().forEach(t=>t.stop());router.replace('/dashboard')};
  if(status==='Connecting…')return <main className="grid h-screen place-items-center bg-slate-950 text-white"><div className="text-center"><div className="mx-auto mb-4 h-10 w-10 animate-spin rounded-full border-2 border-white/20 border-t-indigo-400"/><p>{status}</p></div></main>;
  return <main className="flex h-screen flex-col bg-slate-950 text-white"><header className="flex h-16 items-center justify-between border-b border-white/10 px-5"><div><p className="font-semibold">{meeting?.title||'RTC Meeting'}</p><button onClick={copy} className="mt-0.5 flex items-center gap-1 text-xs text-slate-400 hover:text-white">{code}<Copy size={12}/>{copied&&' Copied'}</button></div><div className="flex items-center gap-2 text-slate-400"><Shield size={16}/><span className="hidden text-xs sm:inline">{status}</span><MoreHorizontal/></div></header><section className="flex min-h-0 flex-1"><div className="relative flex flex-1 items-center justify-center p-4"><div className="relative aspect-video w-full max-w-5xl overflow-hidden rounded-2xl border border-white/10 bg-slate-900"><video ref={videoRef} autoPlay muted playsInline className={`h-full w-full object-cover ${video?'':'hidden'}`}/>{!video&&<div className="absolute inset-0 grid place-items-center"><div className="grid h-20 w-20 place-items-center rounded-full bg-slate-800 text-2xl font-semibold">U</div></div>}<div className="absolute bottom-4 left-4 rounded-lg bg-black/50 px-3 py-1.5 text-xs backdrop-blur">You</div>{sharing&&<div className="absolute right-4 top-4 rounded-lg bg-emerald-500/90 px-3 py-1.5 text-xs font-medium">Screen sharing</div>}</div></div>{chat&&<aside className="hidden w-80 border-l border-white/10 bg-slate-900 p-5 md:block"><div className="flex items-center justify-between"><h2 className="font-semibold">Chat</h2><button onClick={()=>setChat(false)}>×</button></div><p className="mt-3 text-xs text-slate-500">{participants.length} participant{participants.length===1?'':'s'}</p><div className="mt-8 text-center text-sm text-slate-500">Chat is ready for this room.</div></aside>}</section><footer className="flex h-20 items-center justify-center gap-2 border-t border-white/10 bg-slate-950 px-4"><button onClick={()=>toggle('audio')} className={`grid h-12 w-12 place-items-center rounded-full ${audio?'bg-slate-800':'bg-red-500'}`}>{audio?<Mic/>:<MicOff/>}</button><button onClick={()=>toggle('video')} className={`grid h-12 w-12 place-items-center rounded-full ${video?'bg-slate-800':'bg-red-500'}`}>{video?<Video/>:<VideoOff/>}</button><button onClick={share} className={`grid h-12 w-12 place-items-center rounded-full ${sharing?'bg-indigo-500':'bg-slate-800'}`}><MonitorUp/></button><button onClick={()=>setChat(v=>!v)} className="grid h-12 w-12 place-items-center rounded-full bg-slate-800"><MessageSquare/></button><button className="grid h-12 w-12 place-items-center rounded-full bg-slate-800"><Users/></button><button onClick={leave} className="ml-2 grid h-12 w-14 place-items-center rounded-full bg-red-500"><PhoneOff/></button></footer></main>;
}
